# Generated by Django 4.2.14 on 2024-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.IntegerField()),
                ('Alzheimer_Disease', models.IntegerField()),
                ('Overlapping_Symptom', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
