# Generated by Django 4.2.17 on 2025-02-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_patient_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('prediction', models.CharField(max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
